return {
    ---@param cutscene WorldCutscene
    start = function(cutscene)
        local transition = Game.world:getEvent(15)
        local leader = Game.world.player
        cutscene:detachFollowers()
        transition:setPosition(0, transition.y)
        local darkness = Rectangle(0, 0, SCREEN_WIDTH, SCREEN_HEIGHT)
        cutscene:wait(1)
        if #Game.party == 1 then
            leader:setPosition(320, -40)
            cutscene:wait(cutscene:slideToSpeed(leader, leader.x, 320, 20))
            Assets.playSound("impact")
            leader:setSprite("landed")
            cutscene:wait(1)
        elseif #Game.party == 2 then
            local party2 = cutscene:getCharacter(Game.party[2].id)
            leader:setPosition(350, -40)
            party2:setPosition(290, -40)
            cutscene:wait(cutscene:slideToSpeed(leader, leader.x, 320, 20))
            Assets.playSound("impact")
            leader:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party2, party2.x, 320, 20))
            Assets.playSound("impact")
            party2:setSprite("landed")
            cutscene:wait(1)
        elseif #Game.party == 3 then
            local party2 = cutscene:getCharacter(Game.party[2].id)
            local party3 = cutscene:getCharacter(Game.party[3].id)
            leader:setPosition(320, -40)
            party2:setPosition(260, -40)
            party3:setPosition(380, -40)
            cutscene:wait(cutscene:slideToSpeed(leader, leader.x, 320, 20))
            Assets.playSound("impact")
            leader:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party2, party2.x, 320, 20))
            Assets.playSound("impact")
            party2:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party3, party3.x, 320, 20))
            Assets.playSound("impact")
            party3:setSprite("landed")
            cutscene:wait(1)
        elseif #Game.party == 4 then
            local party2 = cutscene:getCharacter(Game.party[2].id)
            local party3 = cutscene:getCharacter(Game.party[3].id)
            local party4 = cutscene:getCharacter(Game.party[4].id)
            leader:setPosition(350, -40)
            party2:setPosition(290, -40)
            party3:setPosition(230, -40)
            party4:setPosition(410, -40)
            cutscene:wait(cutscene:slideToSpeed(leader, leader.x, 320, 20))
            Assets.playSound("impact")
            leader:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party2, party2.x, 320, 20))
            Assets.playSound("impact")
            party2:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party3, party3.x, 320, 20))
            Assets.playSound("impact")
            party3:setSprite("landed")
            cutscene:wait(1)
            cutscene:wait(cutscene:slideToSpeed(party4, party4.x, 320, 20))
            Assets.playSound("impact")
            party4:setSprite("landed")
            cutscene:wait(1)
        end
        cutscene:wait(1)
        transition:setPosition(240, transition.y)
        cutscene:attachFollowers()
        cutscene:interpolateFollowers()
    end,
    dead_end = function(cutscene)
        cutscene:wait(1)
        cutscene:detachCamera()
        cutscene:wait(cutscene:panTo(1840, 240, 1))
        cutscene:wait(1)
        if cutscene:getCharacter("ceroba") then
            cutscene:text("* Ugh,[wait:5] a dead end.[wait:5] Just great.", "muttering", "ceroba")
        elseif cutscene:getCharacter("susie") then
            cutscene:text("* Damn,[wait:5] a dead end.", "annoyed", "susie")
        else
            cutscene:text("* (A dead end.)")
        end
    end
}
